src/SmartCore/Module/Shop/Entity/Order.php
<?php

namespace SmartCore\Module\Shop\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="SmartCore\Module\Shop\Entity\OrderRepository")
 * @ORM\Table(name="shop_orders",
 *      indexes={
 *          @ORM\Index(columns={"created_at"}),
 *          @ORM\Index(columns={"phone"}),
 *          @ORM\Index(columns={"payment_date"}),
 *          @ORM\Index(columns={"payment_status"}),
 *          @ORM\Index(columns={"shipping_status"}),
 *          @ORM\Index(columns={"user_id"}),
 *      }
 * )
 */
class Order
{
    use ColumnTrait\Id;
    use ColumnTrait\Address;
    use ColumnTrait\Comment;
    use ColumnTrait\Email;
    use ColumnTrait\NameNotBlank;
    use ColumnTrait\Phone;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\ExpiresAt;
    use ColumnTrait\UpdatedAt;
    use ColumnTrait\FosUser;

    const STATUS_PENDING    = 0; // Ожидается - находится в корзинке.
    const STATUS_PROCESSING = 1;
    const STATUS_SHIPPING   = 2;
    const STATUS_CANCELLED  = 3;
    const STATUS_FINISHED   = 4;
    const STATUS_DELETED    = 5; // Удалён - в корзине были удалены все товары.

    const PAYMENT_STATUS_NEW       = 0;
    const PAYMENT_STATUS_ABORTED   = 1;
    const PAYMENT_STATUS_COMPLETED = 2;

    const SHIPPING_STATUS_ONHOLD     = 0;
    const SHIPPING_STATUS_READY      = 1; // Готов к отправке
    const SHIPPING_STATUS_CANCELLED  = 2;
    const SHIPPING_STATUS_RETURNED   = 3;
    const SHIPPING_STATUS_INPROGRESS = 4; // В процессе доставки
    const SHIPPING_STATUS_SHIPPED    = 5; // Доставлено

    /**
     * @var int
     *
     * @ORM\Column(type="float")
     */
    protected $amount;

    /**
     * @var int
     *
     * @ORM\Column(type="smallint", options={"default":0})
     */
    protected $status;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    protected $payment_status;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $payment_date;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    protected $shipping_status;

    /**
     * @var OrderItem[]
     *
     * @ORM\OneToMany(targetEntity="OrderItem", mappedBy="order")
     * @ORM\OrderBy({"created_at" = "ASC"})
     */
    protected $order_items;

    /**
     * @var Shipping
     *
     * @ORM\ManyToOne(targetEntity="Shipping")
     */
    protected $shipping;

    /**
     * Constructor.
     */
    public function __construct()
    {
        $this->amount       = 0;
        $this->created_at   = new \DateTime();
        $this->order_items  = new ArrayCollection();
        $this->status       = self::STATUS_PENDING;
    }

    /**
     * @return int
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * @param int $amount
     *
     * @return $this
     */
    public function setAmount($amount)
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * @param OrderItem $orderItem
     *
     * @return $this
     */
    public function addOrderItem(OrderItem $orderItem)
    {
        if (!$this->order_items->contains($orderItem)) {
            $orderItem->setOrder($this);
            $this->order_items->add($orderItem);
        }

        return $this;
    }

    /**
     * @return OrderItem[]|ArrayCollection
     */
    public function getOrderItems()
    {
        return $this->order_items;
    }

    /**
     * @param OrderItem[]|ArrayCollection $order_items
     *
     * @return $this
     */
    public function setOrderItems($order_items)
    {
        $this->order_items = $order_items;

        return $this;
    }

    /**
     * @return \DateTime|null
     */
    public function getPaymentDate()
    {
        return $this->payment_date;
    }

    /**
     * @param \DateTime|null $payment_date
     *
     * @return $this
     */
    public function setPaymentDate(\DateTime $payment_date = null)
    {
        $this->payment_date = $payment_date;

        return $this;
    }

    /**
     * @return string
     */
    public function getPaymentStatus()
    {
        return $this->payment_status;
    }

    /**
     * @param string $payment_status
     *
     * @return $this
     */
    public function setPaymentStatus($payment_status)
    {
        $this->payment_status = $payment_status;

        return $this;
    }

    /**
     * @return string
     */
    public function getShippingStatus()
    {
        return $this->shipping_status;
    }

    /**
     * @param string $shipping_status
     *
     * @return $this
     */
    public function setShippingStatus($shipping_status)
    {
        $this->shipping_status = $shipping_status;

        return $this;
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param int $status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return string
     */
    public function getStatusAsText()
    {
        switch ($this->status) {
            case self::STATUS_PENDING:
                return 'Pending';
                break;
            case self::STATUS_PROCESSING:
                return 'Processing';
                break;
            case self::STATUS_SHIPPING:
                return 'Shipping';
                break;
            case self::STATUS_FINISHED:
                return 'Finished';
                break;
            case self::STATUS_CANCELLED:
                return 'Cancelled';
                break;
            case self::STATUS_DELETED:
                return 'Deleted';
                break;
            default:
                return 'N/A';
        }
    }

    /**
     * @return Shipping
     */
    public function getShipping()
    {
        return $this->shipping;
    }

    /**
     * @param Shipping $shipping
     *
     * @return $this
     */
    public function setShipping($shipping)
    {
        $this->shipping = $shipping;

        return $this;
    }
}

src/SmartCore/Module/Shop/Resources/views/basket_widget.html.twig
<div id="basket_widget" style="margin-bottom: 20px;">
    {% if qty %}
        В вашей <a href="{{ basket_url }}">корзине</a> {{ qty }} товара
        <br/>на сумму {{ order.amount }} рублей
    {% else %}
        Ваша <a href="{{ basket_url }}">корзина</a> пуста
    {% endif %}
</div>

src/SmartCore/Module/Shop/Resources/views/index.html.twig
{{ 'Welcome to new generated module'|trans }}.

src/SmartCore/Module/Shop/Resources/views/my_basket.html.twig
<h3>Моя корзина</h3>

{% if is_granted('ROLE_USER') %}
    {% if items %}
    <div class="row">
        <div class="span12 col-sm-12">
            <table class="table table-bordered table-hover">
                <thead><tr>
                    <th>Наименование</th>
                    <th>Кол-во</th>
                    <th>Цена</th>
                    <th>Сумма</th>
                    <th>Дата</th>
                </tr></thead>
                <tbody>
                {% for orderItem in items %}
                    <tr>
                        <td>
                            {{ smart_media_img(orderItem.item.attr('image'), '100x100') }}
                            {{ orderItem.item.attr('title') }}
                        </td>
                        <td>
                            <button class="btn btn-default" onclick="alert('@todo: Сделать как у OZON.')">{{ orderItem.quantity }}</button>
                            <form action="" method="post" style="display: inline-block;">
                                <input type="hidden" name="_node_id" value="{{ node_id }}" />
                                <input type="hidden" name="order_item_id" value="{{ orderItem.id }}" />
                                <button class="btn btn-danger" onclick="return confirm('Вы уверены, что хотите удалить товар из корзиты?')" name="remove" title="Удалить">X</button>
                            </form>
                        </td>
                        <td>{{ orderItem.item.attr('price') }}</td>
                        <td>{{ orderItem.amount }}</td>
                        <td>{{ orderItem.createdAt|date('Y-m-d H:i:s') }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <p>Итого: <b>{{ order.amount }}</b> рублей</p>

            <p><a class="btn btn-success" href="{{ path('smart_module.shop.checkout') }}">Оформить заказ</a></p>
        </div>
    </div>
    {% else %}
        <p>Корзина пуста.</p>
    {% endif %}
{% else %}
    <p><i>Пожалуйста <a href="{{ path('fos_user_registration_register') }}">зарегистрируйтесь</a>
            или <a href="{{ path('fos_user_profile_show') }}">войдите</a>
            для получения возможности оформлять заказы в интернет магазине.
        </i></p>
{% endif %}

src/SmartCore/Module/Shop/Resources/views/order.html.twig
<h2>Оформление заказа</h2>

<h4>Товары</h4>

<table class="table table-bordered table-hover">
    <thead><tr>
        <th>Наименование</th>
        <th>Цена</th>
        <th>Кол-во</th>
        <th>Сумма</th>
    </tr></thead>
    <tbody>
    {% for orderItem in items %}
        <tr>
            <td>
                {{ orderItem.item.attr('title') }}
            </td>
            <td>{{ orderItem.item.attr('price') }}</td>
            <td>{{ orderItem.quantity }} шт.</td>
            <td>{{ orderItem.amount }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<p style="float: right;">Итого: <b>{{ order.amount }}</b> рублей</p>

<div style="clear: both;"></div>

{% if form is defined %}
    {% form_theme form '@CMS/Form/bootstrap_wide.html.twig' %}
{% endif %}

<style media="all" type="text/css">
    .form-button {
        margin: 3px 0px 5px 20px;
        float: left;
    }
    label span {
        color: red;
    }
    .form-horizontal {
        margin: 5px 0 5px;
    }
    .form-horizontal .control-group {
        margin-bottom: 12px;
    }
    .form-horizontal .control-label {
        float: left;
        width: 200px;
        padding-right: 5px;
    }
    .form-horizontal .controls {
        margin-left: 210px;
    }
    .form-horizontal option[selected=selected] {
        color: blue;
        font-weight: bold;
    }
    .form-vertical .checkbox,
    label.checkbox
    {
        margin-left: 20px;
    }
</style>

{{ form(form, {'attr':{'class': '__form-horizontal'}}) }}

src/SmartCore/Module/Shop/Resources/views/orders.html.twig
<h3>Мои заказы</h3>

{{ knp_menu_render('ShopModuleBundle:Client:orders', {
        'currentClass': 'active',
        'clear_matcher': false,
    })
}}

<div class="row">
    <div class="span12 col-sm-12">
        <table class="table table-bordered table-hover">
            <thead><tr>
                <th>Id</th>
                <th>Товары</th>
                <th>Сумма</th>
                <th>Статус</th>
                <th>Дата</th>
            </tr></thead>
            <tbody>
            {% for order in orders %}
                <tr>
                    <td>{{ order.id }}</td>
                    <td>
                        <ol>
                        {% for item in order.orderitems %}
                            <li>{{ item.title }} ({{ item.quantity }} шт по {{ item.price }} руб.)</li>
                        {% endfor %}
                        </ol>
                    </td>
                    <td>{{ order.amount }}</td>
                    <td>{{ order.statusAsText }}</td>
                    <td>{{ order.createdAt|date('Y-m-d H:i:s') }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

src/SmartCore/Module/Shop/Resources/views/show_buy_button.html.twig
{% if is_granted('ROLE_USER') %}
    <form action="{{ basket_url }}" method="post">
        <input type="hidden" name="_node_id" value="{{ basket_node_id }}" />
        <input type="hidden" name="item_id" value="{{ item_id }}" />
        <button class="btn btn-primary" title="id: {{ item_id }}" name="add">Добавить в корзину</button>
    </form>
{% else %}
    <button class="btn btn-default" title="id: {{ item_id }}" disabled="disabled">Добавить в корзину</button>
    <p><i><span class="asterisk" style="color: rgba(255, 83, 72, 0.66);">*</span>
        Пожалуйста <a href="{{ path('fos_user_registration_register') }}">зарегистрируйтесь</a>
        или <a href="{{ path('fos_user_profile_show') }}">войдите</a>
        для получения возможности оформлять заказы в интернет магазине.
    </i></p>
{% endif %}